import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from 'next/font/google'
import cx from 'classnames'
import Header from "@/components/features/Header/Header";
import {Providers} from "@/providers/provider";
import {ToastContainer} from "react-toastify";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" data-theme="">
      <body className={cx('bg-base-200 relative', inter.className)}>
        <Providers>
          <div className="container-fluid mx-3">

            <div className="pt-3"></div>

            <Header/>

            <div className="flex flex-col">
              {children}
            </div>

          </div>
          <ToastContainer position="bottom-right"/>
        </Providers>
      </body>
    </html>
  )
}
